---
title: "Untitled"
author: "Josemari"
date: "11/3/2020"
output: html_document
---

```{r}
# Load libraries.
library(ggplot2)
library(reshape2)
library(dplyr)
library(tidyr)
library(data.table)
# Load the datasets.
load("meat.Rdata")
load("oliveoil.Rdata")
head(oliveoil)
```

```{r}
### Task 1 ###
# 1. Create a vector with wavelenght values from 400 to 2498 in step of two.
wlval <- seq(400, 2498, 2)

# 2. Plot the first observation agains the wavelenths.
# Get the first observation values without he first column, which is the type of meat.
# Use unlist to obtain only a vector of values instead of a df with col names.
firstchick <- unlist(meatdata[1, -1], use.names = FALSE)
# Plot a line plot.
plot(wlval, firstchick, type = "l",
     ylab = "Reflectance values", xlab = "Wavelenght", main = "Chicken 1 spectrum")
```
```{r}
# 3. Get the median, first quartile and third quartile of each column.
# Create three empty vectors to store each data type.
medians <- c()
frstqs <- c()
thrdqs <- c()
# Create indices for all the wavelength columns, excluding the first column which is the type columng.
indices <- c(2:length(colnames(meatdata)))
# Loop through the columns and append each value to the respective vector.
for (index in indices) {
  medians <- c(medians, median(meatdata[, index]))
  frstqs <- c(frstqs, quantile(meatdata[, index], 0.25))
  thrdqs <- c(thrdqs, quantile(meatdata[, index], 0.75))
}

# 4. Produce a plot that shows the median, first quartile and third quartile for each wavelength.
# Create a dataframe with the stats and the wavelengths.
statsdf <- data.frame(wlval, medians, frstqs, thrdqs)
# Format the data so each value gets a key that will be the name of the vector it is in.
# Exclude the wavelenthgs as those will be the x axis.
statsplot <- statsdf %>% gather (key, value, -wlval)
# Plot the median, first and third quartiles agains the wavelengths.
ggplot(statsplot, mapping = aes(x = wlval, y = value, color = key)) +
  geom_line() +
  xlab("Wavelengths (nm)") +
  ylab("Reflectance values") +
  ggtitle("Stats summary for each wavelength") +
  # Format the legend.
  scale_colour_discrete(name = "Stats",
                        breaks = c("frstqs", "medians", "thrdqs"), # original names.
                        labels = c("1st quantile", "Median", "3rd quantile")) # new names.
```
```{r}
# 5. Calculate the median value of each column of the data for each meat type and plot these.
# Subset the dataset depending on the meat type.
chicken_meat <- subset(meatdata, Type == "Chicken")
beef_meat <- subset(meatdata, Type == "Beef")
lamb_meat <- subset(meatdata, Type == "Lamb")
pork_meat <- subset(meatdata, Type == "Pork")
turkey_meat <- subset(meatdata, Type == "Turkey")
# Start empty vectors to store the median of each meat type.
chicken_median <- c()
beef_median <- c()
lamb_median <- c()
pork_median <- c()
turkey_median <- c()

# Fill the empty vectors with the corresponding values.
for (index in indices){
  chicken_median <- c(chicken_median, median(chicken_meat[, index]))
  beef_median <- c(beef_median, median(beef_meat[, index]))
  lamb_median <- c(lamb_median, median(lamb_meat[, index]))
  pork_median <- c(pork_median, median(pork_meat[, index]))
  turkey_median <- c(turkey_median, median(turkey_meat[, index]))
}

# Create a df with the medians of each meat and the wavelengths.
meatmeddf <- data.frame(wlval, chicken_median, beef_median, lamb_median, pork_median, turkey_median)
# Format the data so each value gets a key that will be the name of the vector it is in.
# Exclude the wavelenthgs as those will be the x axis.
meatmedplot <- meatmeddf %>% gather (key, value, -wlval)
# Get the meat type names.
meat_types <- c(levels(meatdata$Type))
# Plot the median, first and third quartiles agains the wavelengths.
ggplot(meatmedplot, mapping = aes(x = wlval, y = value, color = key)) +
  geom_line() +
  xlab("Wavelengths (nm)") +
  ylab("Reflectance values") +
  ggtitle("Different meat values for each wavelength") +
  scale_colour_discrete(name = "Meat type",
                        breaks = c("beef_median",
                                   "chicken_median",
                                   "lamb_median",
                                   "pork_median",
                                   "turkey_median"),
                        labels = meat_types)

```
```{r}
# 6. Create a new factor variable that combines the Chicken and Turkey samples into Poultry.
poultry_meat <- rbind(chicken_meat, turkey_meat)

# 7. Re-do the calculation in (6) with the new factor variable as the meat type.
# I assume with 6 you mean 5, as in 6 there are no calculations. Re-do calcs and plot with poultry.
poultry_median <- c()
for (index in indices) {
  poultry_median <- c(poultry_median, median(poultry_meat[, index]))
}
poultrydf <- data.frame(wlval, poultry_median, beef_median, lamb_median, pork_median)
head(poultrydf)
poultryplot <- poultrydf %>% gather (key, value, -wlval)
ggplot(poultryplot, mapping = aes(x = wlval, y = value, color = key)) +
  geom_line() +
  xlab("Wavelengths (nm)") +
  ylab("Reflectance values") +
  ggtitle("Different meat values with poultry for each wavelength") +
  scale_colour_discrete(name = "Meat type",
                        breaks = c("beef_median",
                                   "lamb_median",
                                   "pork_median",
                                   "poultry_median"),
                        labels = c("Beef", "Lamb", "Pork", "Poultry"))

```
```{r}
### Task 2 ###
# 1. Write the function.
df_plot <- function(dataframe){
  
  # Get the wavelenghts.
  wlval <- seq(400, 2498, 2)
  # Get the unique types of the dataframe.
  df_types <- unique(dataframe$Type)
  # Make a list with all the names for the results matrix.
  result_names <- c("Wavelengths")
  for (type in df_types) {
    result_names <- c(result_names, paste0(type, "_median"))
    result_names <- c(result_names, paste0(type, "_frstq"))
    result_names <- c(result_names, paste0(type, "_thrdq"))
  }
  # Create an empty matrix with rows and columns depending on the input dataframe.
  # Columns are one less because we won't count the type column, as it is now in the rowname.
  df.results = matrix(nrow = length(result_names), ncol = ncol(dataframe) - 1)
  rownames(df.results) <- result_names
  # Fill the first row with the wavelengths.
  df.results[1,] <- wlval
  # Set the current row to start as the second, to not overwrite the row 1 with the wavelengths.
  current_row = 2
  # Loop through the types and the index of the columns.
  for (type in df_types) {
    for (indexcol in 2:ncol(dataframe)){
      # Calculate the stats for each type and add it to the respective possition on the results matrix.
      current_subset = which(dataframe$Type == type)
      current_median = median(dataframe[current_subset, indexcol])
      current_frstq = quantile(dataframe[current_subset, indexcol], 0.25)
      current_thrdq = quantile(dataframe[current_subset, indexcol], 0.75)
      df.results[current_row, indexcol - 1] = current_median
      df.results[current_row + 1, indexcol - 1] = current_frstq
      df.results[current_row + 2, indexcol - 1] = current_frstq
    }
    # Once the 3 stats for one type are filled, jump to the next tripplet of rows for the next type.
    current_row <- current_row + 3
  }
  # Remove unnecesary column and convert it to a dataframe.
  colnames(df.results) <- df.results[1,]
  df.results = df.results[-1,]
  df.results <- as.data.frame(df.results)
  
  # Transpose the df and rename the col and row names.
  t_dfresults <- transpose(df.results)
  colnames(t_dfresults) <- rownames(df.results)
  rownames(t_dfresults) <- colnames(df.results)
  
  # Format the dataframe for easy plotting.
  t_dfresults <- cbind(wlval, t_dfresults)
  resultsplot <- t_dfresults %>% gather (key, value, -wlval)
  p <- ggplot(resultsplot, mapping = aes(x = wlval, y = value, color = key)) + geom_line() +
    xlab("Wavelengths (nm)") +
    ylab("Reflectance values") +
    geom_vline(xintercept=700, colour="red")
  
  return(p)
}
# Get the plots for the meat data and the olive oil data.
df_plot(meatdata)
df_plot(oliveoil)

```

```{r}
### Task 3 ###
df_stats <- function(dataframe){
  
  # Get the wavelenghts.
  wlval <- seq(400, 2498, 2)
  # Get the unique types of the dataframe.
  df_types <- unique(dataframe$Type)
  # Make a list with all the names for the results matrix.
  result_names <- c("Wavelengths")
  for (type in df_types) {
    result_names <- c(result_names, paste0(type, "_median"))
    result_names <- c(result_names, paste0(type, "_frstq"))
    result_names <- c(result_names, paste0(type, "_thrdq"))
  }
  # Create an empty matrix with rows and columns depending on the input dataframe.
  # Columns are one less because we won't count the type column, as it is now in the rowname.
  df.results = matrix(nrow = length(result_names), ncol = ncol(dataframe) - 1)
  rownames(df.results) <- result_names
  # Fill the first row with the wavelengths.
  df.results[1,] <- wlval
  # Set the current row to start as the second, to not overwrite the row 1 with the wavelengths.
  current_row = 2
  # Loop through the types and the index of the columns.
  for (type in df_types) {
    for (indexcol in 2:ncol(dataframe)){
      # Calculate the stats for each type and add it to the respective possition on the results matrix.
      current_subset = which(dataframe$Type == type)
      current_median = median(dataframe[current_subset, indexcol])
      current_frstq = quantile(dataframe[current_subset, indexcol], 0.25)
      current_thrdq = quantile(dataframe[current_subset, indexcol], 0.75)
      df.results[current_row, indexcol - 1] = current_median
      df.results[current_row + 1, indexcol - 1] = current_frstq
      df.results[current_row + 2, indexcol - 1] = current_frstq
    }
    # Once the 3 stats for one type are filled, jump to the next tripplet of rows for the next type.
    current_row <- current_row + 3
  }
  # Remove unnecesary column and convert it to a dataframe.
  colnames(df.results) <- df.results[1,]
  df.results = df.results[-1,]
  df.results <- as.data.frame(df.results)
  
  
  return(df.results)
}

# subset the results only with the values on the visible spectrum.
visib_wvl <- seq(400, 700, 2)
visib_limit <- which(wlval==700)
visible_oil <- df_stats(oliveoil)[,1:visib_limit]

# Format the df and plot it
t_visible <- transpose(visible_oil)
colnames(t_visible) <- rownames(visible_oil)
rownames(t_visible) <- colnames(visible_oil)
t_visible <- cbind(visib_wvl, t_visible)
visibleplot <- t_visible %>% gather (key, value, -visib_wvl)
ggplot(visibleplot, mapping = aes(x = visib_wvl, y = value, color = key)) + geom_line() +
  xlab("Wavelengths (nm)") +
  ylab("Reflectance values") +
  ggtitle("Oil values for the visible spectra") +
  # Add vertical lines for the different colors on the visible spectrum.
  geom_vline(xintercept=400, colour="purple") +
  geom_vline(xintercept=470, colour="blue") +
  geom_vline(xintercept=550, colour="green") +
  geom_vline(xintercept=600, colour="yellow") +
  geom_vline(xintercept=630, colour="orange") +
  geom_vline(xintercept=665, colour="red")
  
```
